select * from products;

select * from CATEGORIES;

select * from UZYTKOWNIK;

drop table test34.CATEGORIES;
CREATE TABLE  CATEGORIES
  (
    CATEGORYID NUMBER (*,0) NOT NULL ,
    CATEGORYNAME NVARCHAR2 (15) NOT NULL ,
    DESCRIPTION NCLOB ,
    PICTURE VARCHAR(250) NULL
  );
  
 / 
ALTER TABLE  CATEGORIES ADD CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORYID) ;
/

drop table PRODUCTS;
CREATE TABLE  PRODUCTS
  (
    PRODUCTID NUMBER (*,0) NOT NULL ,
    PRODUCTNAME NVARCHAR2 (40) ,
    SUPPLIERID NUMBER (*,0) ,
    CATEGORYID NUMBER (*,0) ,
    QUANTITYPERUNIT NVARCHAR2 (20) ,
    UNITPRICE    NUMBER ,
    UNITSINSTOCK NUMBER (*,0) ,
    UNITSONORDER NUMBER (*,0) ,
    REORDERLEVEL NUMBER (*,0) ,
    DISCONTINUED NUMBER
  );
/
ALTER TABLE  PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCTID);
/

ALTER TABLE  PRODUCTS ADD CONSTRAINT PRODUCTS_CATEGORIES_FK FOREIGN KEY (CATEGORYID) 
REFERENCES  CATEGORIES (CATEGORYID) ;
/

drop sequence seq_CATEGORIES;
/
create sequence seq_CATEGORIES;
/
CREATE OR REPLACE TRIGGER ADD_ID_CATEGORIES
before insert on CATEGORIES
for each row
begin
  if :new.CATEGORYID is null or :new.CATEGORYID=0 then
select seq_CATEGORIES.nextval into :new.CATEGORYID from dual
 end if
end;
commit
drop sequence seq_PRODUCTS;
/
create sequence seq_PRODUCTS;
/
 CREATE OR REPLACE TRIGGER ADD_ID_PRODUCTS
before insert on PRODUCTS
for each row
begin
  if :new.PRODUCTID is null or :new.PRODUCTID=0 then
    select seq_PRODUCTS.nextval into :new.PRODUCTID from dual
 end if
end;
/
CREATE TABLE UZYTKOWNIK (
ID NUMBER(22) NOT NULL ,
UIMIE VARCHAR2(15) NOT NULL, 
UMIASTO VARCHAR2(15) NOT NULL, 
UNAZWISKO VARCHAR2(25) NOT NULL, 
UNRLOKALU VARCHAR2(6) NOT NULL, 
UPATENT VARCHAR2(25) NOT NULL, 
UPESEL VARCHAR2(21) NOT NULL, 
UTELEFON VARCHAR2(20) NOT NULL, 
UULICA VARCHAR2(30) NOT NULL, 
NIDFK NUMBER(22) NOT NULL, 
RIDFK NUMBER(22) NOT NULL, 
PRIMARY KEY (ID))
/
CREATE TABLE OBRAZ (
ID NUMBER(22) NOT NULL, 
PLIK BLOB NULL, 
JIDFK NUMBER(22) NULL, 
PRIMARY KEY (ID))

/
ALTER TABLE OBRAZ ADD CONSTRAINT FK_OBRAZ_JIDFK FOREIGN KEY (JIDFK) REFERENCES CATEGORIES (CATEGORYID);

insert into categories(CATEGORYNAME,DESCRIPTION) values ('Spining','New Categories');

commit

select * from products;



create sequence seq_UZYTKOWNIK;
/
CREATE OR REPLACE TRIGGER ADD_ID_UZYTKOWNIK
before insert on UZYTKOWNIK
for each row
begin
  if :new.UZYTKOWNIK is null or :new.UZYTKOWNIK=0 then
select seq_UZYTKOWNIK.nextval into :new.UZYTKOWNIK from dual
 end if
end;
commit